# Generated by Django 3.1.4 on 2024-07-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_vls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(default=0)),
                ('tag', models.CharField(max_length=255)),
                ('alternate_name', models.CharField(max_length=255, null=True)),
                ('tag_type', models.IntegerField(default=0)),
                ('tag_status', models.IntegerField(default=1)),
                ('description', models.TextField(max_length=1024, null=True)),
                ('image_path', models.CharField(max_length=1024, null=True)),
                ('user_generated_indicator', models.BooleanField(default=False)),
                ('added_to_topics_indicator', models.BooleanField(default=False)),
                ('popular_indicator', models.BooleanField(default=False)),
                ('creating_user', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'db_table': 'common_tag',
            },
        ),
    ]
